### ISSUE TITLE
[Bug]Sync error: Reference error: blob is not defined

### ISSUE THREAD

**Issue by yiqiaowang-arch** [windingwind/zotero-better-notes#550]
**Describe the bug**
This bug appeared since July 1st, after using external Markdown editor (Typora) to edit my notes. 
<img width="800" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/28997207/dbc1c990-cbf4-4219-91fe-f92c6690827d">
In previous issue #502 I saw exactly the same error, and I have already updated the betternote plugin to 1.0.4 version.

Message from Zotero-Help-Report Errors:
```
[JavaScript Error: "Passing a URI to Zotero.File.getContentsAsync() is deprecated -- use Zotero.HTTP.request() instead"]

[JavaScript Error: "XML Parsing Error: not well-formed
Location: jar:file:///C:/Users/wangy/AppData/Roaming/Zotero/Zotero/Profiles/f71lf6p2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js
Line Number 1, Column 13:" {file: "jar:file:///C:/Users/wangy/AppData/Roaming/Zotero/Zotero/Profiles/f71lf6p2.default/extensions/Knowledge4Zotero@windingwind.com.xpi!/chrome/content/scripts/editorScript.js" line: 1 column: 13 source: ""use strict";"}]

[JavaScript Error: "Error in parsing the value ‘’ for ‘columnspacing’ attribute of <mtable/>.  Attribute ignored." {file: "resource://zotero/note-editor/editor.html" line: 0}]

version => 6.0.26, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-US, appName => Zotero, appVersion => 6.0.26, extensions => Zotero LibreOffice Integration (6.0.4.SA.6.0.26, extension), Zotero Word for Windows Integration (6.0.3.SA.6.0.26, extension), ZotFile (5.1.2, extension), Zotero Citation Counts Manager (1.3.0, extension), Zutilo Utility for Zotero (3.10.0, extension), Zotero Better Notes (1.0.4, extension), Zotero PDF Translate (1.0.23, extension)
```

**Comment by yiqiaowang-arch** [comment]
# Add: Ways to reproduce the bug
Today I realized that I added a local image in my .md files via Typora with md grammar (see below). When I delete the image from .md file, the sync issue disappeared. 

## Evidences
In .md files, the source code is different than the images added directly from Zotero.
In md files, image that is added directly from Zotero (for example, copy image into clipboard and then directly paste it in note) have a sourcecode like this:
### image from zotero
![image](https://github.com/windingwind/zotero-better-notes/assets/28997207/87167685-c2c8-4512-a30f-e204d53ef7a7)
**zotero image source code example:**
```![\<img alt="" data-attachment-key="P4D7A55I" width="1296" height="576" src="attachments/P4D7A55I.png" ztype="zimage">](attachments/P4D7A55I.png)```

### Image from Typora
However, when I copy image directly into Typora, it uses markdown grammar to link the image to a local storage.
![image](https://github.com/windingwind/zotero-better-notes/assets/28997207/e5c3b5d3-5f0c-490e-bf39-449a3f00d086)
**typora image source code example:**
```![image-20230702195944813](C:\Users\wangy\OneDrive\Typora\Feedback-Principles-MS8R9LKI.assets\image-20230702195944813.png)```


Hope it helps!

**Comment by windingwind** [comment]
#502 

It's fixed in the latest beta

**Comment by soarinsky1** [comment]
The same question still exist：a local image in my .md files via vscode   can't Sync
sync error : referrenceerror: blob is not defined
