### ISSUE TITLE
[Bug] List acts as ghost section heading

### ISSUE THREAD

**Issue by slevey087** [windingwind/zotero-better-notes#82]
**Describe the bug**
I'm having a problem with section headings and lists. I have a numbered list in a section, and the workspace seems to be interpreting that as a heading, but not displaying an item for it in the heading list. When I click the section heading above the list, it works as expected. When I click what should be the next section heading, the note jumps to the top of the list, rather than the next section. All subsequent headings are then offset (by an amount that appears to be equal to the list length), such the clicking them does not take you to a heading at all, but to the middle of paragraphs.

**To Reproduce**
Not quite sure. I've tried making a few lists and this only seems to happen sometimes, I'm not sure when or why. Maybe length? It's a fairly long list that's causing the problem.

**Expected behavior**
Subject headings that jump to the right places in the text, regardless of the presence of lists in between.

**Screenshots**
N/A I think.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Zotero desktop app
 - Zotero version 6.0.9, Better Notes 0.6.0

**Additional context**
This happened after I copied a list from google docs to the note, so I thought it might be that, but then I tried copying the text by hand into a new list in Zotero, and it behaved the same.

**Comment by windingwind** [comment]
Thanks. Currently, the jump is to one line before the heading and the list will be recognized as one line.
I'll set the jump to the heading line in the next update.

**Comment by windingwind** [comment]
fixed in v0.6.1

**Comment by slevey087** [comment]
Thank you for the swift reply and change, but the update didn't fix my issue. Let me put in a few pictures to demonstrate...

Here you can see the section heading just before the table. It works correctly: if you click it in the outline, it jumps right to that heading.
![image](https://user-images.githubusercontent.com/28959396/177372267-b3e047c4-2cca-400c-a629-faf86d067bae.png)

Here you can see I've clicked the next heading in the outline, which should jump to the section below, but it does not, it jumps to the start of the table.
![image](https://user-images.githubusercontent.com/28959396/177372494-28cf04c0-f518-4674-9c73-3a8c55517bab.png)

For reference, the actual location it should be jumping to is much further down, about 80 lines below where the table ends.

Now, all subsequent subject headings no longer jump to the actual location of the subject heading. They jump to locations in the middle of paragraphs. For example, here's what it looks like if I click the next heading. The heading it should be jumping to is much further down the page.
![image](https://user-images.githubusercontent.com/28959396/177372881-66f75855-df99-445e-baca-8370a15ed573.png)

Thanks again for your time and attention!

**Comment by windingwind** [comment]
Please try v0.6.2
